# Credentials to interact with  contact form

credentials:
  Administrator:
    email: automation.sk2017@gmail.com
    password: test!23sk
  Contact:
    email: automationsk007@gmail.com
    password: test!23sk

Execution:
  host: docs.google.com/forms/u/0/
  browser: chrome
  max_wait_time: 20
  min_wait_time: 3